//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperAdvertisementManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Required(ErrorMessage = "Name cannot be empty")]
        [RegularExpression("^[a-zA-Z ]{2,40}$", ErrorMessage = "Name should contain alphabets only")]
        [DisplayName("Admin Name")]
        public string AdminName { get; set; }
        [Required(ErrorMessage = "Email cannot be empty!")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email is invalid.")]
        [DisplayName("Admin Email")]
        [DataType(DataType.EmailAddress)]
        public string AdminEmailId { get; set; }
        [Required(ErrorMessage = "Mobile number can't be blank.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Mobile number should be of 10 digits.")]
        [Range(0, 9999999999)]
        [DisplayName("Admin Phone")]
        public string AdminPhone { get; set; }
        [Required(ErrorMessage = "Password cannot be empty!")]
        [RegularExpression(@"((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,15})", ErrorMessage = "Password should be 6 to 15 characters with at least one digit, one uppercase letter, one lower case letter.")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string AdminPassword { get; set; }
    }
}
