//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperAdvertisementManagement.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.ReportProblems = new HashSet<ReportProblem>();
        }
    
        public int AdvertisementNo { get; set; }
        [Required]
        [DisplayName("Advertisement Name")]
        public string AdvertisementName { get; set; }
        [Required]
        [DisplayName("Customer EmailId")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Email is invalid.")]
        public string CustomerEmailId { get; set; }
        [Required]
        [DisplayName("Advertisement Description")]
        public string AdvertisementDescription { get; set; }
        [Required (ErrorMessage ="Please upload Image")]
        [DisplayName("Advertisement Image")]
        public string AdvertisementImage { get; set; }
        [Required]
        [DisplayName("Advertisement Dimension")]
        public string AdvertisementDimension { get; set; }
        [Required]
        [DisplayName("Advertisement Price")]
        public decimal AdvertisementPrice { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Advertisement Date")]
        public System.DateTime AdvertisementDate { get; set; }

        public string AdvertisementStatus { get; set; }
        public HttpPostedFileBase imageFile { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportProblem> ReportProblems { get; set; }
    }
}
