//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPaperAdvertisementManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReportProblem
    {
        public int ReportId { get; set; }
        public int AdvertisementNo { get; set; }
        public string CustomerEmailId { get; set; }
        [Required]
        public string ReportType { get; set; }
        [Required]
        public string ReportDescription { get; set; }
    
        public virtual Advertisement Advertisement { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
